name: Cotninuous Deployment

on:
  push:
    branches:
      - main

env:
  FUNCTION_NAME: GrimoireLambdaFunction

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push Docker Image to Amazon ECR and Update Lambda Function
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: grimoire-lambda
          IMAGE_TAG: latest
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG Grimoire.Lambda/src/Grimoire.Lambda
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          aws lambda update-function-code --function-name ${{ env.FUNCTION_NAME }} --image-uri $REGISTRY/$REPOSITORY:$IMAGE_TAG
